version: 2.1

orbs:
  python: circleci/python@0.3.0
  codecov: codecov/codecov@1.0.5

jobs:
  build-and-test:
    working_directory: ~/pylabber
    docker:
      - image: themattrix/tox
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DB_NAME: circle_test
          DB_USER: root
          DB_PASSWORD: password
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: Disable xdebug
          command: |
            sudo sed -i 's/^zend_extension/;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip
      - run:
          name: Install libpq-dev
          command: apt update && apt install -y libpq-dev
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Create blank tests env file
          command: touch pylabber/.env
      - run:
          name: Test using tox
          command: tox
      - codecov/upload:
          file: coverage.xml
          flags: unittests

workflows:
  main:
    jobs:
      - build-and-test
